# Generated by Django 4.0 on 2022-11-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('estado', models.IntegerField(default=0)),
                ('horas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AREAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=4, verbose_name='Nombre del area')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='COORDINACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(verbose_name='Nombre de la coordinación')),
            ],
        ),
        migrations.CreateModel(
            name='FICHAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.TextField()),
                ('nom', models.TextField()),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.TextField()),
                ('nom', models.TextField()),
                ('idncl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.ncl')),
            ],
        ),
        migrations.CreateModel(
            name='TITULACION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(verbose_name='codigo de la titulacion')),
                ('nom', models.TextField()),
                ('idarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.areas')),
            ],
        ),
        migrations.CreateModel(
            name='RAP_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.actividad')),
                ('idrap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.rap')),
            ],
        ),
        migrations.AddField(
            model_name='ncl',
            name='idtitulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.titulacion'),
        ),
        migrations.CreateModel(
            name='FICHAS_ACTIVIDAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idactividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.actividad')),
                ('idfichas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.fichas')),
            ],
        ),
        migrations.AddField(
            model_name='fichas',
            name='idtitulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.titulacion'),
        ),
        migrations.AddField(
            model_name='areas',
            name='idcoordina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.coordinacion'),
        ),
    ]
