# Generated by Django 4.0 on 2022-11-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_rename_areas_area_rename_fichas_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.IntegerField(default=1, verbose_name=(('ACTIVO', 1), ('INACTIVO', 2))),
        ),
    ]
