# Generated by Django 4.0 on 2022-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_actividad_estado_alter_ficha_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nom',
            field=models.CharField(max_length=30, verbose_name='Nombre del area'),
        ),
    ]
