# Generated by Django 4.0 on 2022-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_area_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rap',
            name='cod',
            field=models.TextField(max_length=30),
        ),
    ]
