# Generated by Django 4.0 on 2022-11-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_rap_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rap',
            name='cod',
            field=models.CharField(max_length=30),
        ),
    ]
