# Generated by Django 4.0 on 2022-11-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_rap_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncl',
            name='des',
        ),
        migrations.AlterField(
            model_name='ncl',
            name='cod',
            field=models.TextField(max_length=15),
        ),
    ]
