# Generated by Django 4.0 on 2022-11-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_remove_ncl_des_alter_ncl_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncl',
            name='cod',
            field=models.CharField(max_length=15),
        ),
    ]
